package com.example.proyecto.demo.dto;

import com.example.proyecto.demo.Entity.Registro1;

import java.time.LocalDate;

public record PerfilCompletoDTO(
        Long id,
        String nombre,
        String apellidoPaterno,
        String apellidoMaterno,
        String email,
        String curp,
        String rfc,
        String telefono,
        String celular,
        String tipoIdentificacionOficial,
        String identificacionOficial,
        String calle,
        String numeroExterior,
        String numeroInterior,
        String entreCalle,
        String yCalle,
        String otraReferencia,
        String colonia,
        String claveLocalidad,
        String localidad,
        String claveMunicipio,
        String municipioDomicilio,
        String claveEntidadFederativa,
        String codigoPostal,
        String claveAgeb,
        String claveRedSocial,
        String redSocial,
        String genero,
        LocalDate fechaNacimiento,
        String nacionalidad,
        String paisNacimiento,
        String entidadFederativa,
        String municipio,
        String estadoCivil,
        String tipoPerfil,
        Boolean tienePerfilMigracion,
        String visibilidadPerfil,
        Boolean consentimientoDirectorioPublico,
        String gradoAcademico,
        Long fotoDocumentoId,
        Long curriculumDocumentoId,
        Long ineDocumentoId,
        Long domicilioDocumentoId,
        Long cedulaDocumentoId,
        Long constanciaSniiDocumentoId,
        String cedulaProfesional,
        String semblanza,
        Boolean registro2Completo
) {
    public static PerfilCompletoDTO from(com.example.proyecto.demo.Entity.Usuario usuario) {
        Registro1 reg = usuario.getRegistro1();
        boolean tienePerfil = usuario.getPerfilMigracion() != null;
        return new PerfilCompletoDTO(
                usuario.getId(),
                usuario.getNombre(),
                usuario.getApellidoPaterno(),
                usuario.getApellidoMaterno(),
                usuario.getAuthUser() != null ? usuario.getAuthUser().getEmail() : null,
                reg != null ? reg.getCurp() : null,
                reg != null ? reg.getRfc() : null,
                reg != null ? reg.getTelefono() : null,
                reg != null ? reg.getCelular() : null,
                reg != null ? reg.getTipoIdentificacionOficial() : null,
                reg != null ? reg.getIdentificacionOficial() : null,
                reg != null ? reg.getCalle() : null,
                reg != null ? reg.getNumeroExterior() : null,
                reg != null ? reg.getNumeroInterior() : null,
                reg != null ? reg.getEntreCalle() : null,
                reg != null ? reg.getYCalle() : null,
                reg != null ? reg.getOtraReferencia() : null,
                reg != null ? reg.getColonia() : null,
                reg != null ? reg.getClaveLocalidad() : null,
                reg != null ? reg.getLocalidad() : null,
                reg != null ? reg.getClaveMunicipio() : null,
                reg != null ? reg.getMunicipioDomicilio() : null,
                reg != null ? reg.getClaveEntidadFederativa() : null,
                reg != null ? reg.getCodigoPostal() : null,
                reg != null ? reg.getClaveAgeb() : null,
                reg != null ? reg.getClaveRedSocial() : null,
                reg != null ? reg.getRedSocial() : null,
                reg != null && reg.getGenero() != null ? reg.getGenero().name() : null,
                reg != null ? reg.getFechaNacimiento() : null,
                reg != null ? reg.getNacionalidad() : null,
                reg != null ? reg.getPaisNacimiento() : null,
                reg != null ? reg.getEntidadFederativa() : null,
                reg != null ? reg.getMunicipio() : null,
                reg != null && reg.getEstadoCivil() != null ? reg.getEstadoCivil().name() : null,
                reg != null && reg.getTipoPerfil() != null ? reg.getTipoPerfil().name() : null,
                tienePerfil,
                usuario.getVisibilidadPerfil() != null ? usuario.getVisibilidadPerfil() : "ESTANDAR",
                Boolean.TRUE.equals(usuario.getConsentimientoDirectorioPublico()),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                usuario.getSemblanza(),
                Boolean.TRUE.equals(usuario.getRegistro2Completo())
        );
    }
}
